version: "3"

services:
  db-mysql:
    image: mysql:5.7
    networks:
      - tourists
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: tourists

  php-fpm:
    build: 
      context: ./tourists-php
    image: gcr.io/tourists-280412/tourists-php:latest
    volumes:
      - tourists:/var/www/html/
    networks:
      - tourists

  server:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: gcr.io/tourists-280412/tourists-server:latest
    depends_on:
      - db-mysql
      - php-fpm
    volumes:
     - tourists:/var/www/html/
    ports:
      - 80:80
    networks:
      - tourists

networks: 
  tourists:

volumes:
  tourists: