version: "3"

services:
  tourists-mysql:
    image: mysql:5.7
    networks:
      - tourists
    environment:
      MYSQL_ROOT_PASSWORD: Y3sS0fT
      MYSQL_DATABASE: tourists

  php-fpm:
    image: php:fpm-alpine3.12
    volumes:
      - tourists:/var/www/html/
    networks:
      - tourists

  server:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: gcr.io/tourists-280412/tourists-server:latest
    depends_on:
      - tourists-mysql
      - php-fpm
    volumes:
     - tourists:/var/www/html/
    ports:
      - 80:80
    networks:
      - tourists

networks: 
  tourists:

volumes:
  tourists: