on: [push]

jobs:
  backend_deploy:
    steps:
      # Cleaning everything up
      - name: Checkout
        uses: actions/checkout@v2
      # Building and pushing symfony
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io
          path: ./dev_symfony
          dockerfile: ./server.Dockerfile
          repository: tourists-280412
          tags: project_container:latest
      # Building and pushing nginx server
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: gcr.io
          path: ./nginx
          repository: tourists-280412
          tags: tourists_project_server:latest
      