name: 'Hello Actions!'
author: 'Mohammad Al Kalaleeb'

on: 
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
    # Cleaning everything up
    - name: Checkout
      uses: actions/checkout@v2
    
    # Building and pushing symfony  
    - name: Build and push Symfony Container image
      uses: docker/build-push-action@v1
      env:
        DOCKER_BUILDKIT: 1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        path: ./dev_symfony
        dockerfile: ./server.Dockerfile
        repository: tourists-280412
        tags: project_container:latest
      
    # Building and pushing nginx server
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        path: ./nginx
        repository: tourists-280412
        tags: tourists_project_server:latest
      