apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourists-nginx
  labels:
    app: tourists
spec:
  selector:
    matchLabels:
      app: tourists
      tier: balancer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tourists
        tier: balancer
    spec:
      containers:
      - name: tourists-nginx
        image: gcr.io/tourists-280412/tourists-server:latest
        ports:
        - name: nginx-port
          containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html"
            name: backend
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: touristsClaim