apiVersion: v1
kind: Service
metadata:
  name: tourists-nginx
  labels:
    app: tourists
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tourists
    tier: balancer
  type: LoadBalancer
  # loadBalancerIP: "35.242.240.161"