apiVersion: v1
kind: Service
metadata:
  name: tourists-backend
  labels:
    app: tourists
spec:
  ports:
  - port: 7000
    protocol: TCP
  selector:
    app: tourists
    tier: backend
  clusterIP: None

---

apiVersion: v1
kind: Service
metadata:
  name: tourists-backend-master
  labels:
    app: tourists
spec:
  ports:
  - port: 7000
    protocol: TCP
  selector:
    app: tourists
    tier: backend
  clusterIP: None
  