apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: touristsClaim
spec:
  accessModes:
    - ReadWrite
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  storageClassName: slow
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [dev]}