App\Request\ImageCreateRequest:
  properties:
    path:
      - NotBlank: ~

App\Request\AcceptedOrderCreateRequest:
  properties:
    date:
      - NotBlank: ~
    touristUserID:
      - NotBlank: ~
    orderID:
      - NotBlank: ~
    guidUserID:
      - NotBlank: ~
    cost:
      - NotBlank: ~

App\Request\CommentCreateRequest:
  properties:
    date:
      - NotBlank: ~
    comment:
      - NotBlank: ~
    user:
      - NotBlank: ~

App\Request\EventCreateRequest:
  properties:
    date:
      - NotBlank: ~
    name:
      - NotBlank: ~
    type:
      - NotBlank: ~
    status:
      - NotBlank: ~
    location:
        - NotBlank: ~
    description:
      - NotBlank: ~

App\Request\GuidRegisterRequest:
  properties:
    userID:
      - NotBlank: ~

App\Request\GuidProfileCreateRequest:
  properties:
    user:
      - NotBlank: ~

App\Request\RatingCreateRequest:
  properties:
    user:
      - NotBlank: ~
    rate:
      - NotBlank: ~

App\Request\RegionCreateRequest:
  properties:
    name:
      - NotBlank: ~
    description:
      - NotBlank: ~

App\Request\TouristOrderCreateRequest:
  properties:
    date:
      - NotBlank: ~
    touristUserID:
      - NotBlank: ~
    city:
      - NotBlank: ~
    language:
      - NotBlank: ~
    arriveDate:
      - NotBlank: ~
    leaveDate:
      - NotBlank: ~

App\Request\TouristRegisterRequest:
  properties:
    userID:
      - NotBlank: ~