apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apache
  name: tourist-webserver
  namespace: tourist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - image: gcr.io/pc-api-6479467557629758909-343/github_yes-soft-de_tourist
          imagePullPolicy: Always
          name: php-apache
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/upload/image
              name: tourist-pvc-sym-m
      tolerations:
        - effect: NoExecute
          key: env
          operator: Equal
          value: dev
      volumes:
        - name: tourist-pvc-sym-m
          persistentVolumeClaim:
            claimName: tourist-pvc-sym-uploud
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: apache
  name: tourist-webserver-service
  namespace: tourist
spec:
  clusterIP: 10.4.2.58
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: apache
  sessionAffinity: None
  type: ClusterIP
