name: tourists
description: Tourists App

publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.0

    # Localization Library
    flutter_localizations:
        sdk: flutter

    # DI
    provider: ^4.3.2+2

    # Dependency injection
    inject:
        git:
            url: https://github.com/yes-soft-de/inject.dart.git
            path: package/inject

    # Shared Prefs
    shared_preferences: ^0.5.12

    # Network Agent
    dio: ^3.0.10
    dio_flutter_transformer: ^3.0.2
    dio_http_cache: ^0.2.11

    # Pair and Other Types
    analyzer_plugin: ^0.3.0

    # String validation
    validators: ^2.0.1

    # Retrofit
    retrofit: ^1.3.4

    # Logger
    logger: any

    # Streams and RX
    rxdart: ^0.24.1

    # ORM, Database SQL
    sqfentity: ^1.4.0+1

    # Firebase Libs
    firebase_core: ^0.5.0
    firebase_auth: ^0.18.1+1
    firebase_analytics: ^6.0.1
    firebase_remote_config: ^0.4.0+1
    cloud_firestore: ^0.14.1+2

    # Localization
    gen_lang: 0.1.3

    # Internationalization
    intl: ^0.16.1
    intl_translation: ^0.17.10
    intl_utils: ^1.7.0

    # Toasts
    fluttertoast: ^7.1.1

    # UUID
    uuid: ^2.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    # Various Build Time Functions
    build_runner: ^1.10.1

    # For Testing
    test: ^1.15.4

    # Country Dropdown
    country_pickers: ^1.3.0

    # Analyzer for DI
    analyzer: ^0.39.5

    # DI
    inject_generator:
        git:
            url: https://github.com/yes-soft-de/inject.dart.git
            path: package/inject_generator

    # Generate Language Files
    lang_table: 0.2.0

    # Icons Generator
    flutter_launcher_icons: "^0.7.3"

flutter:
    uses-material-design: true

    assets:
        #  - resources/fonts
        #   - images/a_dot_burr.jpeg
        #   - images/a_dot_ham.jpeg
        - resources/images/

    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #

flutter_intl:
    enabled: true

flutter_icons:
    android: "launcher_icon"
    ios: true
    image_path: "resources/images/logo.png"